### ISSUE TITLE
Build #137 has some DNS / tracker connectivity issues

### ISSUE THREAD

**Issue by neo21670** [linuxserver/docker-deluge#49]
**Host OS:** Debian 9 (OMV 4 default)
**Docker:** latest CE stable

I am updating my containers with watchtower. Today, build 137 was pushed on Docker Hub and I noticed my torrents were down with the tracker status '*name*: tracker unavailable' for all possible trackers. I verified and trackers were up and running and were accessible from any other client. Both container, host and hypervisor clocks are in sync and updated by NTP hourly.

I tried restarting the container and the VM hosting Docker. Neither bore any results - after restart all trackers were slowly polled and were unreachable. From the container I can ping any trackers so it doesn't seem to be a network connectivity issue. I have not tried other operations.

Considering these I rolled back to build 136. Startup with previous configuration had no issues, all my settings were retained. After everything loaded, all tracker statuses were back to normal '*name*: Announce OK'.

**Comment by leomoty** [comment]
I have noticed the same, also rolled back to 136. Running Fedora Server 28 with Docker CE.

**Comment by yoyellow** [comment]
Same issue; rolled back to 136 fixed it.  running latest docker on latest debian.

**Comment by neo21670** [comment]
I am totally unsure about the origins but would like to note, that some other container that experienced a similiar issue back then had its OpenSSL upgraded to a newer one with hardened default setting. Worth checking

**Comment by noxzobax** [comment]
same here. 

[INFO    ] 10:46:21 server:650 Starting server in PID 210.
[INFO    ] 10:46:21 server:664 serving on 0.0.0.0:8112 view at http://127.0.0.1:8112
[INFO    ] 10:46:21 client:217 Connecting to daemon at 127.0.0.1:58846..
[INFO    ] 10:46:21 client:217 Connecting to daemon at 127.0.0.1:58846..
[INFO    ] 10:46:21 client:121 Connected to daemon at 127.0.0.1:58846..
[INFO    ] 10:46:21 client:121 Connected to daemon at 127.0.0.1:58846..
[INFO    ] 10:46:26 client:217 Connecting to daemon at 127.0.0.1:58846..
[INFO    ] 10:46:26 client:217 Connecting to daemon at 127.0.0.1:58846..
[INFO    ] 10:46:26 client:121 Connected to daemon at 127.0.0.1:58846..
[INFO    ] 10:46:26 client:121 Connected to daemon at 127.0.0.1:58846..
[INFO    ] 10:46:28 client:217 Connecting to daemon at 127.0.0.1:58846..
[INFO    ] 10:46:28 client:121 Connected to daemon at 127.0.0.1:58846..
[INFO    ] 10:46:29 client:224 Connection lost to daemon at 127.0.0.1:58846 reason: Connection to the other side was lost in a non-clean fashion: Connection lost.
[INFO    ] 10:46:29 client:224 Connection lost to daemon at 127.0.0.1:58846 reason: Connection to the other side was lost in a non-clean fashion: Connection lost.
[INFO    ] 10:46:29 client:224 Connection lost to daemon at 127.0.0.1:58846 reason: Connection to the other side was lost in a non-clean fashion: Connection lost.
[INFO    ] 10:46:29 client:224 Connection lost to daemon at 127.0.0.1:58846 reason: Connection to the other side was lost in a non-clean fashion: Connection lost.
[INFO    ] 10:46:29 client:224 Connection lost to daemon at 127.0.0.1:58846 reason: Connection to the other side was lost in a non-clean fashion: Connection lost.
[INFO    ] 10:46:29 server:681 Shutting down webserver

rollback to the version 136, everything is fine

**Comment by aaomidi** [comment]
Same here.

**Comment by luchtgitaar** [comment]
+1

**Comment by leomoty** [comment]
Did anyone test build #138? It seems to be available now. I'll try when I get home.

**Comment by yoyellow** [comment]
issue persist in 138, rollback to 136 still required for working DNS

**Comment by gderf** [comment]
I also had to roll back as far as Tag:136. Tags 137, 138, and latest are broken.

**Comment by JigSawFr** [comment]
Same problem, need to roll back to 136

**Comment by OmgImAlexis** [comment]
@sparklyballs can you please look into this.

**Comment by gderf** [comment]
Fixed in Tag:139

**Comment by ben-ba** [comment]
all versions above 136 (137,138,139) doesn't work for me, because the daemon (deluged) won't start.
Config files core.conf and auth are missing.

**Comment by noxzobax** [comment]
Still the same problem with the version 140 (same if I add missing conf file):

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing... 
usermod: no changes

User uid:    911
User gid:    911

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[INFO    ] 12:43:34 configmanager:70 Setting config directory to: /config
[INFO    ] 12:43:34 ui:124 Deluge ui 1.3.15
[INFO    ] 12:43:34 ui:127 Starting web ui..
[WARNING ] 12:43:35 config:364 Unable to open config file /config/web.conf: [Errno 2] No such file or irectory: '/config/web.conf'
[WARNING ] 12:43:35 config:364 Unable to open config file /config/hostlist.conf.1.2: [Errno 2] No such 
 file or directory: '/config/hostlist.conf.1.2'
[WARNING ] 12:43:35 config:423 Unable to open config file: /config/hostlist.conf.1.2 because: [Errno 2] No such file or directory: '/config/hostlist.conf.1.2'
[WARNING ] 12:43:35 config:443 Unable to backup old config...
[INFO    ] 12:43:35 server:666 Starting server in PID 215.
[INFO    ] 12:43:35 server:679 Serving on 0.0.0.0:8112 view at http://0.0.0.0:8112
[INFO    ] 12:43:56 auth:327 Login success (ClientIP 172.17.0.1)
[INFO    ] 12:43:58 client:217 Connecting to daemon at 127.0.0.1:58846..
[INFO    ] 12:43:58 client:217 Connecting to daemon at 127.0.0.1:58846..
[WARNING ] 12:43:58 client:220 Connection to daemon at 127.0.0.1:58846 failed: Connection was refused by other side: 111: Connection refused.
[WARNING ] 12:43:58 client:220 Connection to daemon at 127.0.0.1:58846 failed: Connection was refused by other side: 111: Connection refused.
[INFO    ] 12:44:00 client:217 Connecting to daemon at 127.0.0.1:58846..
[WARNING ] 12:44:00 client:220 Connection to daemon at 127.0.0.1:58846 failed: Connection was refused by other side: 111: Connection refused.
[WARNING ] 12:44:03 config:423 Unable to open config file: /config/web.conf because: [Errno 2] No such file or directory: '/config/web.conf'
[WARNING ] 12:44:03 config:443 Unable to backup old config...

**Comment by homerr** [comment]
Can somebody confirm whether this is present in the latest releases please?

**Comment by leomoty** [comment]
@homerr also seems to work fine here.
